### PR TITLE
Deployed application in Heroku

### LINKED ISSUE #6: Deploy application on Heroku

### PR DESCRIPTION
**Pull request by soorajbhaskaran**
Fixes #6 
All my code updates have successfully merged into the `master` branch.
This is the[ link ](https://soorajbhskrn-neetouichallenge.herokuapp.com/login)to my hosted application in Heroku.
Credentials:
```
Email ID: oliver@example.com
Password: welcome
```
Please review.

### CODE REVIEW

**Comment by yedhink** [comment]
@soorajbhskrn https://www.loom.com/share/9fd07d2c4a92418394e4a96491255eb4

**Comment by soorajbhaskaran** [comment]
I have made a loom video explaining why I haven't added you as the reviewer in some of the PR. Please lemme know if this is not the right way of doing it in this situation.
https://www.loom.com/share/cd1c14ed7c214ac9a87aa5e0e5a60553

**Comment by yedhink** [comment]
Read: https://handbook.neetokb.com/articles/git-and-github-essentials#pr-branch

And the logistics you've followed is so confusing to me. It's actually a very simple process.
- You make PR
- You merge PR
- You assign me the PR for review
- I add review comments
- You make the changes via next feature PR or make a separate PR just for the review comments

**Comment by soorajbhaskaran** [comment]
Thanks, Yedhin for the insights. I think I missed[ this](https://handbook.neetokb.com/articles/git-and-github-essentials#pr-branch) part of the handbook. I will make sure to follow these practices while raising a PR in the future.

**Comment by yedhink** [comment]
@soorajbhskrn Please create a short video and point out what you have understood about https://handbook.neetokb.com/articles/git-and-github-essentials#pr-branch. You can put that video in #ch2022 Slack channel. The point of this video is to ensure others in the channel also know about this practice. 

Thanks.

**Comment by soorajbhaskaran** [comment]
I have posted a video explaining [this](https://handbook.neetokb.com/articles/git-and-github-essentials#pr-branch) in #ch2022 slack channel.  Also, I have updated all the changes suggested in my latest commit in this PR. Please review.

**Comment by yedhink** [comment]
LGTM. You can mark this task as completed and go ahead with the next one.

**Pull request merged**
